-- MySQL Script generated by MySQL Workbench
-- 04/07/17 00:49:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema seal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seal` DEFAULT CHARACTER SET utf8 ;
USE `seal` ;

-- -----------------------------------------------------
-- Table `seal`.`papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`papel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `perfil_id` INT NOT NULL DEFAULT 2,
  `matricula` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `turma` VARCHAR(45) NOT NULL,
  `ano` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_perfil_idx` (`perfil_id` ASC),
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `seal`.`papel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`tentativas_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`tentativas_login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tentativas_login_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_tentativas_login_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `seal`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `professor_id` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `ano` YEAR NOT NULL,
  `semestre` VARCHAR(8) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_turma_usuario1_idx` (`professor_id` ASC),
  CONSTRAINT `fk_turma_usuario1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `seal`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`turma_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`turma_usuario` (
  `id` INT NOT NULL,
  `turma_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turma_has_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_turma_has_usuario_turma1_idx` (`turma_id` ASC),
  CONSTRAINT `fk_turma_has_usuario_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `seal`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `seal`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`nivel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`avaliacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `turma_id` INT NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `data` DATE NOT NULL,
  `conteudo` VARCHAR(45) NOT NULL,
  `nota` FLOAT NOT NULL,
  `staus` CHAR(1) NOT NULL DEFAULT '1',
  `nivel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacao_turma1_idx` (`turma_id` ASC),
  INDEX `fk_avaliacao_nivel1_idx` (`nivel_id` ASC),
  CONSTRAINT `fk_avaliacao_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `seal`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_nivel1`
    FOREIGN KEY (`nivel_id`)
    REFERENCES `seal`.`nivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`questoes_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`questoes_avaliacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `avaliacao_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  `numero` INT(2) NOT NULL,
  `pergunta` VARCHAR(450) NOT NULL,
  `a` VARCHAR(450) NULL,
  `b` VARCHAR(450) NULL,
  `c` VARCHAR(450) NULL,
  `d` VARCHAR(450) NULL,
  `e` VARCHAR(450) NULL,
  `resposta` CHAR(1) NULL,
  `nivel` INT(1) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questoes_tipo1_idx` (`tipo_id` ASC),
  INDEX `fk_questoes_avaliacao1_idx` (`avaliacao_id` ASC),
  CONSTRAINT `fk_questoes_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `seal`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questoes_avaliacao1`
    FOREIGN KEY (`avaliacao_id`)
    REFERENCES `seal`.`avaliacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`resposta_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`resposta_avaliacao` (
  `idresposta` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `questoes_id` INT NOT NULL,
  `alternativa` CHAR(1) NULL,
  `algoritmo` TEXT NULL,
  PRIMARY KEY (`idresposta`),
  INDEX `fk_resposta_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_resposta_questoes1_idx` (`questoes_id` ASC),
  CONSTRAINT `fk_resposta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `seal`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resposta_questoes1`
    FOREIGN KEY (`questoes_id`)
    REFERENCES `seal`.`questoes_avaliacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `turma_id` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `nivel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividade_turma1_idx` (`turma_id` ASC),
  INDEX `fk_atividade_nivel1_idx` (`nivel_id` ASC),
  CONSTRAINT `fk_atividade_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `seal`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividade_nivel1`
    FOREIGN KEY (`nivel_id`)
    REFERENCES `seal`.`nivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`questoes_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`questoes_atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `atividade_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  `numero` INT(2) NOT NULL,
  `pergunta` VARCHAR(450) NOT NULL,
  `nivel` INT(1) NOT NULL,
  `a` VARCHAR(450) NULL,
  `b` VARCHAR(450) NULL,
  `c` VARCHAR(450) NULL,
  `d` VARCHAR(450) NULL,
  `e` VARCHAR(450) NULL,
  `resposta` CHAR(1) NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questoes_copy1_atividade1_idx` (`atividade_id` ASC),
  INDEX `fk_questoes_copy1_tipo1_idx` (`tipo_id` ASC),
  CONSTRAINT `fk_questoes_copy1_atividade1`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `seal`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questoes_copy1_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `seal`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seal`.`resposta_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seal`.`resposta_atividade` (
  `idresposta` INT NOT NULL AUTO_INCREMENT,
  `questoes_resposta_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `alternativa` CHAR(1) NULL,
  `algoritmo` TEXT NULL,
  PRIMARY KEY (`idresposta`),
  INDEX `fk_resposta_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_resposta_avaliacao_copy1_questoes_copy11_idx` (`questoes_resposta_id` ASC),
  CONSTRAINT `fk_resposta_usuario10`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `seal`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resposta_avaliacao_copy1_questoes_copy11`
    FOREIGN KEY (`questoes_resposta_id`)
    REFERENCES `seal`.`questoes_atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
